version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
  
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'desafio'
      POSTGRES_HOST: 'localhost'
    volumes:
      - /docker/postgres/volumes:/var/lib/postgresql/data  

  
    
   